import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettierConfig,
  {
    // Same scope eslint-config-next loads its React plugin for. Without it
    // this block also applied to scripts/*.cjs (the Turbopack strip
    // loader), where the plugin isn't defined, and ESLint refused to run.
    // Every file that can contain JSX is still covered.
    files: ["**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
    rules: {
      // Hard rule from CLAUDE.md: this product renders text from websites
      // we do not control. dangerouslySetInnerHTML is banned repo-wide, no exceptions.
      "react/no-danger": "error",
      // Convention for an intentionally-unused destructured binding, e.g.
      // omitting one field from a fixture via `const { x: _x, ...rest } = obj`.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // The Turbopack strip loader must be CommonJS (webpack's loader-runner
    // `require`s it), so `require()` is the correct import style there.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx msw init` - not our code, has its own directives.
    "public/mockServiceWorker.js",
    // Generated by `npx shadcn add sidebar` - hand-editing it (e.g. to
    // satisfy react-hooks/set-state-in-effect) would fight shadcn's smart-
    // merge update workflow for a file we didn't author.
    "src/hooks/use-mobile.ts",
  ]),
]);

export default eslintConfig;
