import type { Metadata } from "next";
import { Cormorant_Garamond, Montserrat } from "next/font/google";
import "./globals.css";

// Heading typeface. Weight 300 only - see docs/DESIGN_SYSTEM_APP.md.
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  weight: "300",
  subsets: ["latin"],
});

// UI/body typeface, full 300-700 range for uppercase labels at 600-700.
const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${cormorantGaramond.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
